### ISSUE TITLE
Fix icons

### ISSUE THREAD

**Issue by douglasshimada** [zsinx6/dojo-toolkit#2]
I ran the program and the icon is missing when the message pop up

**Comment by zsinx6** [comment]
Are you using ubuntu with unity? according to this: https://wiki.ubuntu.com/NotificationDevelopmentGuidelines
the daemon in unity does not allow inline images

`from pgi.repository import Notify, GdkPixbuf`
`...`
`self.red = GdkPixbuf.Pixbuf.new_from_file("r.jpg")`
`...`
`self.notification.update('NOT OK TO TALK', '', 'r.jpg')`
`self.notification.set_image_from_pixbuf(self.red)`

this should fix? try it and tell

**Comment by zsinx6** [comment]
fixed in lasted version
